# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'upPhoiWindowxdNFzb.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_UpPhoiWindow(object):
    def setupUi(self, UpPhoiWindow):
        if not UpPhoiWindow.objectName():
            UpPhoiWindow.setObjectName(u"UpPhoiWindow")
        UpPhoiWindow.resize(1862, 917)
        UpPhoiWindow.setStyleSheet(u"background-color: #040f13;")
        self.centralwidget = QWidget(UpPhoiWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMaximumSize(QSize(16777215, 1000))
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.frame_5 = QFrame(self.frame)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setMinimumSize(QSize(0, 0))
        self.frame_5.setMaximumSize(QSize(420, 16777215))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.frame_9 = QFrame(self.frame_5)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame_9)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 60, 111, 21))
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_5 = QLabel(self.frame_9)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 180, 131, 21))
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_8 = QLabel(self.frame_9)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(210, 60, 57, 15))
        self.label_9 = QLabel(self.frame_9)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(240, 120, 20, 21))
        self.label_9.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_10 = QLabel(self.frame_9)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(180, 240, 20, 21))
        self.label_10.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_11 = QLabel(self.frame_9)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(290, 240, 20, 21))
        self.label_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox = QSpinBox(self.frame_9)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(100, 110, 121, 31))
        self.spinBox.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox.setMaximum(99999999)
        self.spinBox_2 = QSpinBox(self.frame_9)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(270, 110, 111, 31))
        self.spinBox_2.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_2.setMaximum(999999)
        self.spinBox_3 = QSpinBox(self.frame_9)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(100, 230, 61, 31))
        self.spinBox_3.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_3.setMaximum(999999)
        self.spinBox_4 = QSpinBox(self.frame_9)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(210, 230, 61, 31))
        self.spinBox_4.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_4.setMaximum(999999)
        self.spinBox_5 = QSpinBox(self.frame_9)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setGeometry(QRect(320, 230, 61, 31))
        self.spinBox_5.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_5.setMinimum(-360)
        self.spinBox_5.setMaximum(360)
        self.label_3 = QLabel(self.frame_9)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 10, 171, 16))
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout_3.addWidget(self.frame_9)

        self.frame_7 = QFrame(self.frame_5)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.frame_8 = QFrame(self.frame_7)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setStyleSheet(u"")
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.label_32 = QLabel(self.frame_8)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 90, 81, 16))
        self.label_32.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_33 = QLabel(self.frame_8)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 130, 81, 16))
        self.label_33.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.comboBox_2 = QComboBox(self.frame_8)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(90, 80, 271, 31))
        self.comboBox_2.setStyleSheet(u"background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.comboBox_3 = QComboBox(self.frame_8)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(90, 120, 271, 31))
        self.comboBox_3.setStyleSheet(u"background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.label_31 = QLabel(self.frame_8)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, -10, 81, 31))
        self.label_31.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout_2.addWidget(self.frame_8)


        self.verticalLayout_3.addWidget(self.frame_7)

        self.frame_6 = QFrame(self.frame_5)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.label_15 = QLabel(self.frame_6)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 10, 361, 21))
        self.label_15.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_16 = QLabel(self.frame_6)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 120, 21, 21))
        self.label_16.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_17 = QLabel(self.frame_6)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 160, 71, 21))
        self.label_17.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_18 = QLabel(self.frame_6)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(0, 200, 71, 21))
        self.label_18.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_20 = QLabel(self.frame_6)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(0, 80, 31, 21))
        self.label_20.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_21 = QLabel(self.frame_6)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(270, 200, 20, 21))
        self.label_21.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_11 = QSpinBox(self.frame_6)
        self.spinBox_11.setObjectName(u"spinBox_11")
        self.spinBox_11.setGeometry(QRect(190, 190, 61, 31))
        self.spinBox_11.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_11.setMaximum(9999999)
        self.spinBox_12 = QSpinBox(self.frame_6)
        self.spinBox_12.setObjectName(u"spinBox_12")
        self.spinBox_12.setGeometry(QRect(80, 190, 61, 31))
        self.spinBox_12.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_12.setMaximum(9999999)
        self.spinBox_13 = QSpinBox(self.frame_6)
        self.spinBox_13.setObjectName(u"spinBox_13")
        self.spinBox_13.setGeometry(QRect(300, 190, 61, 31))
        self.spinBox_13.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_13.setMinimum(-360)
        self.spinBox_13.setMaximum(360)
        self.label_22 = QLabel(self.frame_6)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(160, 200, 20, 21))
        self.label_22.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_23 = QLabel(self.frame_6)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(270, 120, 20, 21))
        self.label_23.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_14 = QSpinBox(self.frame_6)
        self.spinBox_14.setObjectName(u"spinBox_14")
        self.spinBox_14.setGeometry(QRect(190, 110, 61, 31))
        self.spinBox_14.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_14.setMaximum(9999999)
        self.spinBox_15 = QSpinBox(self.frame_6)
        self.spinBox_15.setObjectName(u"spinBox_15")
        self.spinBox_15.setGeometry(QRect(80, 110, 61, 31))
        self.spinBox_15.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_15.setMaximum(9999999)
        self.spinBox_16 = QSpinBox(self.frame_6)
        self.spinBox_16.setObjectName(u"spinBox_16")
        self.spinBox_16.setGeometry(QRect(300, 110, 61, 31))
        self.spinBox_16.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_16.setMinimum(-360)
        self.spinBox_16.setMaximum(360)
        self.label_24 = QLabel(self.frame_6)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(160, 120, 20, 21))
        self.label_24.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_25 = QLabel(self.frame_6)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(270, 160, 20, 21))
        self.label_25.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_17 = QSpinBox(self.frame_6)
        self.spinBox_17.setObjectName(u"spinBox_17")
        self.spinBox_17.setGeometry(QRect(190, 150, 61, 31))
        self.spinBox_17.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_17.setMaximum(9999999)
        self.spinBox_18 = QSpinBox(self.frame_6)
        self.spinBox_18.setObjectName(u"spinBox_18")
        self.spinBox_18.setGeometry(QRect(80, 150, 61, 31))
        self.spinBox_18.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_18.setMaximum(9999999)
        self.spinBox_19 = QSpinBox(self.frame_6)
        self.spinBox_19.setObjectName(u"spinBox_19")
        self.spinBox_19.setGeometry(QRect(300, 150, 61, 31))
        self.spinBox_19.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_19.setMinimum(-360)
        self.spinBox_19.setMaximum(360)
        self.label_26 = QLabel(self.frame_6)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(160, 160, 20, 21))
        self.label_26.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_23 = QSpinBox(self.frame_6)
        self.spinBox_23.setObjectName(u"spinBox_23")
        self.spinBox_23.setGeometry(QRect(80, 70, 61, 31))
        self.spinBox_23.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_23.setMaximum(9999999)
        self.label_29 = QLabel(self.frame_6)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(160, 80, 20, 21))
        self.label_29.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_24 = QSpinBox(self.frame_6)
        self.spinBox_24.setObjectName(u"spinBox_24")
        self.spinBox_24.setGeometry(QRect(300, 70, 61, 31))
        self.spinBox_24.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_24.setMinimum(-360)
        self.spinBox_24.setMaximum(360)
        self.spinBox_25 = QSpinBox(self.frame_6)
        self.spinBox_25.setObjectName(u"spinBox_25")
        self.spinBox_25.setGeometry(QRect(190, 70, 61, 31))
        self.spinBox_25.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.spinBox_25.setMaximum(9999999)
        self.label_30 = QLabel(self.frame_6)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(270, 80, 20, 21))
        self.label_30.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout_3.addWidget(self.frame_6)


        self.horizontalLayout_2.addWidget(self.frame_5)

        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setMinimumSize(QSize(1252, 0))
        self.frame_2.setMaximumSize(QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.frame_3 = QFrame(self.frame_2)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(31, 31, 31);")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 0, 71, 16))
        self.pushButton = QPushButton(self.frame_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(550, 840, 101, 31))
        self.pushButton.setStyleSheet(u"background-color: rgb(46, 52, 54);")
        self.textEdit = QTextEdit(self.frame_3)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(60, 840, 461, 31))
        self.textEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.scrollArea = QScrollArea(self.frame_3)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(20, 30, 671, 801))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 669, 799))
        self.image_label = QLabel(self.scrollAreaWidgetContents)
        self.image_label.setObjectName(u"image_label")
        self.image_label.setGeometry(QRect(10, 10, 641, 771))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.horizontalLayout.addWidget(self.frame_3)

        self.frame_4 = QFrame(self.frame_2)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setStyleSheet(u"\n"
"background-color: rgb(31, 31, 31);")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.frame_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 0, 111, 16))
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_36 = QLabel(self.frame_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(520, 850, 151, 20))
        self.label_36.setStyleSheet(u"\n"
"color: rgb(0, 85, 255);\n"
"text-decoration: underline;")
        self.btn_preview = QPushButton(self.frame_4)
        self.btn_preview.setObjectName(u"btn_preview")
        self.btn_preview.setGeometry(QRect(20, 840, 101, 31))
        self.btn_preview.setStyleSheet(u"background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.scrollArea_2 = QScrollArea(self.frame_4)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(10, 30, 681, 801))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 679, 799))
        self.label_img = QLabel(self.scrollAreaWidgetContents_2)
        self.label_img.setObjectName(u"label_img")
        self.label_img.setGeometry(QRect(10, 10, 641, 771))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        self.horizontalLayout.addWidget(self.frame_4)


        self.horizontalLayout_2.addWidget(self.frame_2)


        self.verticalLayout.addWidget(self.frame)

        UpPhoiWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UpPhoiWindow)

        QMetaObject.connectSlotsByName(UpPhoiWindow)
    # setupUi

    def retranslateUi(self, UpPhoiWindow):
        UpPhoiWindow.setWindowTitle(QCoreApplication.translate("UpPhoiWindow", u"MainWindow", None))
        self.label_4.setText(QCoreApplication.translate("UpPhoiWindow", u"K\u00edch th\u01b0\u1edbc \u1ea3nh 1", None))
        self.label_5.setText(QCoreApplication.translate("UpPhoiWindow", u"V\u1ecb tr\u00ed \u0111\u1eb7t v\u00e0o ph\u00f4i", None))
        self.label_8.setText(QCoreApplication.translate("UpPhoiWindow", u"TextLabel", None))
        self.label_9.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_10.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_11.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_3.setText(QCoreApplication.translate("UpPhoiWindow", u"Thi\u1ebft l\u1eadp \u1ea3nh ph\u00f4i", None))
        self.label_32.setText(QCoreApplication.translate("UpPhoiWindow", u"K\u00edch c\u1ee1 ch\u1eef", None))
        self.label_33.setText(QCoreApplication.translate("UpPhoiWindow", u"Ki\u1ec3u ch\u1eef", None))
        self.label_31.setText(QCoreApplication.translate("UpPhoiWindow", u"Thi\u1ebft l\u1eadp", None))
        self.label_15.setText(QCoreApplication.translate("UpPhoiWindow", u"V\u1ecb tr\u00ed[CHI\u1ec0U NGANG X CHI\u1ec0U D\u1eccC X XOAY CHI\u1ec0U]", None))
        self.label_16.setText(QCoreApplication.translate("UpPhoiWindow", u"H\u1ecd ", None))
        self.label_17.setText(QCoreApplication.translate("UpPhoiWindow", u"Ng\u00e0y sinh", None))
        self.label_18.setText(QCoreApplication.translate("UpPhoiWindow", u"Code", None))
        self.label_20.setText(QCoreApplication.translate("UpPhoiWindow", u"T\u00ean", None))
        self.label_21.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_22.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_23.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_24.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_25.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_26.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_29.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label_30.setText(QCoreApplication.translate("UpPhoiWindow", u"X", None))
        self.label.setText(QCoreApplication.translate("UpPhoiWindow", u"Ph\u00f4i g\u1ed1c", None))
        self.pushButton.setText(QCoreApplication.translate("UpPhoiWindow", u"Browse", None))
        self.image_label.setText("")
        self.label_2.setText(QCoreApplication.translate("UpPhoiWindow", u"Ph\u00f4i ch\u1ec9nh s\u1eeda", None))
        self.label_36.setText(QCoreApplication.translate("UpPhoiWindow", u"Video h\u01b0\u1edbng d\u1eabn", None))
        self.btn_preview.setText(QCoreApplication.translate("UpPhoiWindow", u"Preview", None))
        self.label_img.setText("")
    # retranslateUi

